from __future__ import annotations

# AUTO-GENERATED by scripts/generate_components.py — do not edit by hand.
# Intersection of config.py Literal values and *_REGISTRY keys in each module.
# Torch-free: safe to import without a GPU environment.

ATTENTION_TYPES: list[str] = ['baseline', 'gqa']
MLP_TYPES: list[str] = ['gelu', 'swiglu', 'relu2']
NORM_TYPES: list[str] = ['layernorm', 'rmsnorm']
BLOCK_TYPES: list[str] = ['baseline']

COMPONENTS: dict[str, list[str]] = {
    "attention_types": ATTENTION_TYPES,
    "mlp_types": MLP_TYPES,
    "norm_types": NORM_TYPES,
    "block_types": BLOCK_TYPES,
}
