#!/usr/bin/env python3
"""Regenerate src/slm/model/components.py from the actual registry dicts.

Uses AST parsing — no torch dependency, safe to run in any Python 3.11+ env.
Produces the intersection of config.py Literal values and *_REGISTRY keys so
only keys that are both declared in the config AND wired in the registry appear.
"""
from __future__ import annotations

import ast
import pathlib
import textwrap

ROOT = pathlib.Path(__file__).parent.parent
MODEL_DIR = ROOT / "src" / "slm" / "model"


def extract_dict_keys(filepath: pathlib.Path, var_name: str) -> list[str]:
    tree = ast.parse(filepath.read_text())
    for node in ast.walk(tree):
        # Handle both `x = {...}` (Assign) and `x: type = {...}` (AnnAssign)
        if isinstance(node, ast.Assign):
            targets, value = node.targets, node.value
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            targets, value = [node.target], node.value
        else:
            continue
        for target in targets:
            if isinstance(target, ast.Name) and target.id == var_name:
                if isinstance(value, ast.Dict):
                    return [
                        k.value
                        for k in value.keys
                        if isinstance(k, ast.Constant) and isinstance(k.value, str)
                    ]
    return []


def extract_literal_values(filepath: pathlib.Path, type_alias: str) -> list[str]:
    """Return values from a Literal type alias: MyType = Literal["a", "b", ...]"""
    tree = ast.parse(filepath.read_text())
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == type_alias:
                    val = node.value
                    if isinstance(val, ast.Subscript):
                        slc = val.slice
                        if isinstance(slc, ast.Tuple):
                            return [
                                e.value
                                for e in slc.elts
                                if isinstance(e, ast.Constant) and isinstance(e.value, str)
                            ]
                        if isinstance(slc, ast.Constant):
                            return [slc.value]
    return []


def intersection_ordered(declared: list[str], registered: list[str]) -> list[str]:
    """Keep declared order; include only keys present in both."""
    registered_set = set(registered)
    return [x for x in declared if x in registered_set]


def main() -> None:
    config_path = MODEL_DIR / "config.py"

    declared_attention = extract_literal_values(config_path, "AttentionType")
    declared_mlp = extract_literal_values(config_path, "MLPType")
    declared_norm = extract_literal_values(config_path, "NormType")
    declared_block = extract_literal_values(config_path, "BlockType")

    registered_attention = extract_dict_keys(MODEL_DIR / "attention.py", "ATTENTION_REGISTRY")
    registered_mlp = extract_dict_keys(MODEL_DIR / "mlp.py", "MLP_REGISTRY")
    registered_block = extract_dict_keys(MODEL_DIR / "block.py", "BLOCK_REGISTRY")
    # norm.py uses if/elif rather than a registry dict; treat all declared types as supported
    registered_norm = declared_norm

    attention_types = intersection_ordered(declared_attention, registered_attention)
    mlp_types = intersection_ordered(declared_mlp, registered_mlp)
    norm_types = intersection_ordered(declared_norm, registered_norm)
    block_types = intersection_ordered(declared_block, registered_block)

    content = textwrap.dedent(f"""\
        from __future__ import annotations

        # AUTO-GENERATED by scripts/generate_components.py — do not edit by hand.
        # Intersection of config.py Literal values and *_REGISTRY keys in each module.
        # Torch-free: safe to import without a GPU environment.

        ATTENTION_TYPES: list[str] = {attention_types!r}
        MLP_TYPES: list[str] = {mlp_types!r}
        NORM_TYPES: list[str] = {norm_types!r}
        BLOCK_TYPES: list[str] = {block_types!r}

        COMPONENTS: dict[str, list[str]] = {{
            "attention_types": ATTENTION_TYPES,
            "mlp_types": MLP_TYPES,
            "norm_types": NORM_TYPES,
            "block_types": BLOCK_TYPES,
        }}
    """)

    out = MODEL_DIR / "components.py"
    out.write_text(content)

    print(f"Written {out.relative_to(ROOT)}")
    print(f"  attention_types = {attention_types}")
    print(f"  mlp_types       = {mlp_types}")
    print(f"  norm_types      = {norm_types}")
    print(f"  block_types     = {block_types}")


if __name__ == "__main__":
    main()
